- name: Encrypt disks with LUKS
  ansible.builtin.import_tasks: luks.yml
  tags: [luks]

- name: Disable C-states
  ansible.builtin.import_tasks: cstate.yml
  tags: [cstate]

- name: Switch CPU to performance mode
  ansible.builtin.import_tasks: cpu.yml
  tags: [cpu]
